### ISSUE TITLE
Texture Created in multiple paths with improper settings.

### ISSUE THREAD

**Issue by paultech** [AaronShea/BLUI#62]
Hello,

The U4 Texture creation should have a single place where its created rather than within Resize/Recreate texture, this makes modifications and debugging confusing. It should also enter a error state when GetTexture() is called and no texture is generated rather than creating a blank texture silently.

The texture creation is also missing filter, compression and mip generation settings that are needed for textures that are at very close range to the player or you get blurry due to poor default in filtering.

Can submit a pull if requested.

**Comment by AaronShea** [comment]
I'm revising the code for the first issues you have listed. Rather than just calling the same things as `ResetTexture()` it will just call `ResetTexture()` itself after setting the new width and height.
I'll also be putting a `verifyf()` in `GetTexture()` rather than just making another one to fill the space. 
9b74086 & 941c06a

A lot of this code is over a year old, when this project was really just an experiment.

As for the other issue, a long time ago I looked into tweaking the filter, mipmap, and compression settings, but wasn't able to find any setting that improved the appearance. I'm limited on time because of college right now. If you'd like to look into that issue I'd be happy to merge a pull request.

**Comment by Aricwithana** [comment]
If the code needed for possibly trying to get better inscene renders is able to be added to the mix, our team is more than happy to give it testing!
